### ISSUE TITLE
2fa have to be modified to show double auth in a single passage

### ISSUE THREAD

**Issue by dorvan** [Anthilla/Antd#18]
2fa have to be modified to show double auth in a single passage
merge the 2fa inputs to the token. (name &pass + email+ token)
And add the project name under the company name.

![login_token](https://cloud.githubusercontent.com/assets/848817/8632812/98dccb42-27aa-11e5-8070-e4205a26d0a4.jpg)
![emaillogin](https://cloud.githubusercontent.com/assets/848817/8632813/98dfbc4e-27aa-11e5-8902-5d0dadd130ad.jpg)
![login_project_name](https://cloud.githubusercontent.com/assets/848817/8632814/98e26a98-27aa-11e5-9274-391a82a9c1bc.jpg)

**Comment by Grul-** [comment]
In the second step of this 2FA authentication I merged username and password.
