### ISSUE TITLE
after update with antdsh, antd it's loaded but not started

### ISSUE THREAD

**Issue by dorvan** [Anthilla/Antd#19]
after update with antdsh, antd it's loaded but not started.
Please; close the algorithm cycle.

1- site reachable?
2- version verification
3- local process verification
4- update (download)
5- update (loading/conversion)
6- update (active process management)
7- update (config mount management)
8- known world verification
9- new version process start

![Uploading antsh_longrun_exit.jpg…]()

**Comment by Grul-** [comment]
Fixed and refined the update algorithm.
