### ISSUE TITLE
antd first run after load (also with antdsh) fails; second run win!.  ..but..

### ISSUE THREAD

**Issue by dorvan** [Anthilla/Antd#20]
seems some paths, files, directories are not created as first run.
Please; close the algorithm cycle.

1- verify (5Ws + 1h) https://en.wikipedia.org/wiki/Five_Ws (alo for logs)
2- create or manage (mount) what antd needs
3- start processes
4- load modules
5- Activate it.

![antd_second_run2](https://cloud.githubusercontent.com/assets/848817/8632719/d17908f6-27a7-11e5-9535-9bf5c2dc9078.jpg)
![antd_second_run1](https://cloud.githubusercontent.com/assets/848817/8632720/d19d49aa-27a7-11e5-849d-0a372e9e9761.jpg)
![antd_first_run](https://cloud.githubusercontent.com/assets/848817/8632721/d1a21296-27a7-11e5-84e8-d9c9b077c79d.jpg)

**Comment by Grul-** [comment]
Fixed the boot algorithm.
