### ISSUE TITLE
Directories navigation for custom files creation starts from /framework/antd

### ISSUE THREAD

**Issue by dorvan** [Anthilla/Antd#22]
without the option to go up.

or starts from /
or set .  and .. or up arrow.

![antd_directories](https://cloud.githubusercontent.com/assets/848817/8632697/e207279e-27a6-11e5-93dd-9e79fcb4f73d.jpg)
![antd_directories2](https://cloud.githubusercontent.com/assets/848817/8632700/1330e102-27a7-11e5-9c80-cde22dc8244b.jpg)

**Comment by Grul-** [comment]
I fixed the starting directory and now it's "/". Also you can navigate between directories using the breadcrumb buttons.
