### ISSUE TITLE
in /system/sysctl mask the value net.core.netdev_rss_key

### ISSUE THREAD

**Issue by dorvan** [Anthilla/Antd#25]
it's unuseful and too long, prefer a table compact view.
other diffs and profiles are missing

![antd_sysctl](https://cloud.githubusercontent.com/assets/848817/8632694/c8ad62d6-27a6-11e5-9807-fc7e1ca6ebe9.jpg)

**Comment by Grul-** [comment]
I hid temporarily net.core.netdev_rss_key row and too long values.
