### ISSUE TITLE
Antd web terminal

### ISSUE THREAD

**Issue by dorvan** [Anthilla/Antd#28]
does not work correctly:
1- start from antd path, ls -la show it. it's not masked.
2- commands have not echo or are not accepted
3- cd / move to root, without any possibility to going back or execute anything.
4- no autoscroll present.

![ant_web_terminal_errors and bug1](https://cloud.githubusercontent.com/assets/848817/8632678/2d9715e4-27a6-11e5-8505-53f03a94e8bc.jpg)
![ant_web_terminal_no_autoscroll](https://cloud.githubusercontent.com/assets/848817/8632679/2d9c6486-27a6-11e5-9bd3-c4d511c6ab78.jpg)

**Comment by Grul-** [comment]
I set `/` as default directory, I fixed an error in the `cd` command (so both the `cd` and `cd ..` commands should works), instead the `cd -` command is not impelendet yet and I add an `echo` to make it known.

**Comment by Grul-** [comment]
The terminal doesn't show the result after a command, and yet the command itself works.

**Comment by Grul-** [comment]
I add autoscroll to terminal and I fixed the display of the result in the terminal.
